In [6]:
import numpy as np
from NetworkClasses.Loss import *

# Quantify how wrong a model is

# Categorical Cross-Entropy Loss

\begin{equation}
L_i = - \sum_j{y_{i,j} \log{\hat{y}_{i,j}}}
\end{equation}

- $$L_i$$ - sample loss value
- $$i$$ - is the i-th sample in the set
- $$j$$ - is the label/output index
- $$y$$ - denotes the target values
- $$\hat{y}$$ - denotes the predicted values



- for every sample ($$i$$) Calculate CCE loss

- used to compare a "ground-truth" probability (y) and some predicted distribution ($$\hat{y}$$)

In [7]:
softmax_output = [.7, .1, .2]  # probability distribution
targets = [1, 0 ,0]  # ground-truth , a one-hot vector

CCE_sum = 0
for (idx, x) in enumerate(softmax_output):
    CCE_sum += targets[idx] * np.log(x)

CCE_loss = - CCE_sum

print(CCE_loss)

0.35667494393873245


# -log(correct_class_confidence)
- if its a one-hot vector we can ignore all the 0's

$$L_i = - \log{\hat{y_{i,k}}}$$

In [8]:
softmax_output = [.7, .1, .2]  # probability distribution
targets = [1, 0 ,0]  # ground-truth , a one-hot vector

loss = -np.log(softmax_output[targets.index(1)])

print(loss)

0.35667494393873245


In [9]:
softmax_outputs = np.array([[.7, .1, .2],
                            [.1, .5, .4],
                            [.02, .9, .08]])

class_targets = np.array([[1, 0, 0],
                          [0, 1, 0],
                          [0, 1, 0]])


if len(class_targets.shape) == 1:
    correct_confidences = softmax_outputs[
        range(len(softmax_outputs)),
        class_targets
    ]

# Mask values
# only for one-hot encoded labels
elif len(class_targets.shape) == 2:
    correct_confidences = np.sum(
        softmax_outputs * class_targets,
        axis=1
    )

neg_loss = - np.log(correct_confidences)
average_loss = np.mean(neg_loss)
print(average_loss)

0.38506088005216804


In [10]:
# nesmije ici 0 u CCE loss
y_pred = [0, 1, 0]
y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

print(y_pred_clipped)

[1.000000e-07 9.999999e-01 1.000000e-07]


# Accuracy Calculation

In [14]:
softmax_outputs = np.array([[.7, .2, .1],
                            [.5, .1, .4],
                            [.02, .9, .08]])

class_targets = np.array([0, 1, 1])  # labels for 3 samples
predictions = np.argmax(softmax_outputs, axis=1)

if len(class_targets.shape) == 2:
    class_targets = np.argmax(class_targets, axis=1)

accuracy = np.mean(predictions == class_targets)
print(predictions)
print(class_targets)
print(predictions == class_targets)
print(' acc: ', accuracy )

[0 0 1]
[0 1 1]
[ True False  True]
 acc:  0.6666666666666666
