# Libs

In [11]:
import numpy as np

# First Neuron

In [12]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2  # only one bias per neuron

output = 0

for i in range(len(inputs)):
    output += inputs[i] * weights[i]
output += bias

print(output)

4.8


# A Layer Of Neurons
3 neurons in a layer with 4 inputs

In [13]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, .26, -.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

weights = [weights1, weights2, weights3]

bias1 = 2
bias2 = 3
bias3 = 0.5

biases = [bias1, bias2, bias3]

outputs = []
for neuron in range(3):
    output = 0
    for i in range(len(inputs)):
        output += inputs[i] * weights[neuron][i]
    output += biases[neuron]
    outputs.append(output)

print(outputs)

[4.8, 1.21, 2.385]


In [14]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, .26, -.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

layer_output = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_output.append(neuron_output)

print(layer_output)

[4.8, 1.21, 2.385]


# Dot Product and Vector Addition
- cross product results in a vector
- dot product results in a scalar </br>
- a dot product is the sum od products of consecutive vector elements, both vectors must be of the same size

In [15]:
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


# A Single Neuron With Numpy

In [18]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2  # only one bias per neuron

outputs = np.dot(inputs, weights) + bias
print(outputs)

4.8


# A Layer Of Neurons With Numpy

In [21]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, .26, -.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

layer_output = np.dot(weights, inputs) + biases

print(layer_output)

[4.8   1.21  2.385]


# A Layer Of neurons & A Batch Of Data w/ NumPy

In [24]:
inputs = [[1, 2, 3, 2.5],
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, .26, -.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
