In [1]:
from NetworkClasses.Layers import *
from NetworkClasses.ActivationFunctions import *
from NetworkClasses.Loss import *
import matplotlib.pyplot as plt
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()



In [124]:
X, y = spiral_data(samples=100, classes=3)

# dense layer with 2 input features and 3 output features
dense1 = Layer_Dense(2, 3)
# dense layer with 3 input features and 3 output features
dense2 = Layer_Dense(3, 3)

activation1 = Activation_ReLU()
activation2 = Activation_Softmax()

loss_function = Loss_CategoricalCrossentropy()
#####################

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

######################################

print("Each of the samples has ~33%, this results from the random init of weights (a draw from the normal distribution)")
print(activation2.output[:5])
print("Sum of confidence scores : ")
print(np.sum(activation2.output[:5], axis=1, keepdims=True))
print("Argmax confidence score (returns index) : ")
print(np.argmax(activation2.output[:5], axis=1))

######################################

loss = loss_function.calculate(activation2.output, y)
print(loss)

######################################

predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
    class_targets = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)
print(' acc: ', accuracy )

Each of the samples has ~33%, this results from the random init of weights (a draw from the normal distribution)
[[0.33333334 0.33333334 0.33333334]
 [0.33333337 0.3333344  0.33333224]
 [0.33333334 0.33333546 0.33333117]
 [0.33333424 0.33333397 0.33333182]
 [0.3333364  0.33332857 0.33333504]]
Sum of confidence scores : 
[[1.        ]
 [1.        ]
 [0.99999994]
 [1.        ]
 [1.        ]]
Argmax confidence score (returns index) : 
[0 1 1 0 0]
1.0986035
 acc:  0.4
