In [4]:
import numpy as np

x = [1, 2, 3]
w = [1, 2, 3]
b = -16

xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]

z = xw0 + xw1 + xw2 + b

print(z)

y = max(z, 0)

print(y)

-2
0


In [7]:
a = np.array([1,2,3])
b = np.array([1,2,3])

# we multiply elements at the same position and sum them all to get a scalar
print(np.dot(a,b))

c = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
print(c)

14
14


In [24]:
# a matrix can be thought of as a list of vectors
# if we have a batch of data and multiple layers of neurons
# then we have to perform a dot product for each input

A = np.array([[1,1],
              [1,1]])

B = np.array([[1,1],
              [1,1],
              [1,1]])

y = np.dot(A,B.T)
print(y)

[[1 1 1]
 [1 1 1]]


In [55]:
from NetworkClasses.Layers import *


A = np.array([[2,1],
              [1,1]])

# A = np.array([2,1])


weights = np.array([[1,1],
                    [1,1]])

dense1 = Layer_Dense(2,2)
dense1.weights = weights
print(dense1.weights, '\n')

print(dense1.biases, '\n')

dense1.forward(A)
print(dense1.output)

print(np.dot(A, weights))
print(np.cross(A, weights))

[[1 1]
 [1 1]] 

[[0. 0.]] 

[[3. 3.]
 [2. 2.]]
[[3 3]
 [2 2]]
[1 0]
